version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: character-sheet-backend-prod
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/charactersdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_PROFILES_ACTIVE=prod
    restart: always

  db:
    image: postgres:16
    container_name: charactersheet-db-prod
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=charactersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres