# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    container_name: character-sheet-designer-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:charactersdb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: oscarfonts/h2
    container_name: character-sheet-designer-db
    ports:
      - "9092:9092"
      - "8082:8082"
    environment:
      - H2_OPTIONS:-tcp -tcpAllowOthers -web -webAllowOthers